scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
      - targets: ['node_exporter:9100']
      - targets: ['0.0.0.0:9100']
